buildscript {
    ext.projectName = "mcpq"

    // bukkit API version - lowest compatible Minecraft version
    ext.mcVersion = "1.20.1"
    // version of minecraft.proto file - reflected in git submodule
    ext.majorVersion = "2"
    // version of this plugins iteration - increase by one on change
    ext.minorVersion = "1"
    // TODO: when updating version, also update resources/plugin.yml and README.md


    ext.recommendedGradleVersion = "7.2"

    ext.javaVersion = JavaVersion.VERSION_17
    ext.kotlinVersion = "1.9.0"
    ext.shadowVersion = "7.1.2"

    ext.protobufPlugInVersion = "0.9.4"
    ext.protobufVersion = "4.26.1" // OR "3.25.0"
    ext.coroutinesVersion = "1.7.3"
    ext.grpcVersion = "1.63.0"
    ext.grpcKotlinVersion = "1.4.1"

    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "com.google.protobuf:protobuf-gradle-plugin:$protobufPlugInVersion"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}

plugins {
    id "idea"
    id "org.jetbrains.kotlin.jvm" version "${kotlinVersion}"
    id "com.google.protobuf" version "${protobufPlugInVersion}"
    id "com.github.johnrengelman.shadow" version "${shadowVersion}"
}

version "$majorVersion.$minorVersion"
group "com.github.mcpq"

repositories {
    mavenCentral()
    maven {
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        url = "https://oss.sonatype.org/content/groups/public/"
    }
}

dependencies {
    // paper api - Minecraft version dependent
    compileOnly "io.papermc.paper:paper-api:$mcVersion-R0.1-SNAPSHOT"

    // fix compile java alla https://github.com/grpc/grpc-java/issues/4725
    compileOnly "javax.annotation:javax.annotation-api:1.3.2" // Needed for gRPC Java

    // coroutines
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion"

    // grpc
    implementation "com.google.protobuf:protobuf-java:$protobufVersion"
    implementation "com.google.protobuf:protobuf-kotlin:$protobufVersion"
    // implementation "com.google.protobuf:protobuf-java-util:$protobufVersion"

    // for rpc io (server and stubs)
    implementation "io.grpc:grpc-netty-shaded:$grpcVersion"
    // compileOnly("org.apache.tomcat:annotations-api:6.0.53")
    // implementation "io.grpc:grpc-protobuf:$grpcVersion"
    implementation("io.grpc:grpc-protobuf:$grpcVersion") {
        exclude group: "com.google.protobuf", module: "protobuf-java"
    }
    implementation "io.grpc:grpc-stub:$grpcVersion"
    implementation "io.grpc:grpc-kotlin-stub:$grpcKotlinVersion"
}

// make sure that grpc-protobuf (and others) do not use an older protobuf version internally
configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "com.google.protobuf") {
            useVersion(protobufVersion)
            because("protobuf-java must match protoc and generated code version")
        }
        if (requested.group == "io.grpc") {
            if (requested.name == "grpc-kotlin-stub" || requested.name == "protoc-gen-grpc-kotlin") {
                useVersion(grpcKotlinVersion)
            } else {
                useVersion(grpcVersion)
            }
        }
    }
}


protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:$protobufVersion"
    }

    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion"
        }

        grpckt {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:$grpcKotlinVersion:jdk8@jar"
        }
    }

    generateProtoTasks {
        all().each { task ->
            task.plugins {
                // Generate Java gRPC classes
                grpc { }
                // Generate Kotlin gRPC using the custom plugin from library
                grpckt { }
            }
//            task.builtins {
//                kotlin { }
//            }
        }
    }
}

artifacts {
    archives shadowJar
}
jar {
    enabled = false // Disable the default non-shaded jar
}
shadowJar {
    archiveClassifier.set("") // This makes the shaded jar replace the normal one
//    mergeServiceFiles()

    relocate "com.google.protobuf", "shadow.com.google.protobuf"
    relocate "io.grpc", "shadow.io.grpc"
    relocate "kotlinx.coroutines", "shadow.kotlinx.coroutines"

    outputs.upToDateWhen { false } // (optional, for dev)
}

tasks.build {
    dependsOn(shadowJar)
}

compileKotlin {
    kotlinOptions.jvmTarget = javaVersion
//    kotlinOptions.javaParameters = true
//    java.targetCompatibility = javaVersion
//    java.sourceCompatibility = javaVersion
//    java.toolchain.languageVersion = JavaLanguageVersion.of(17)
}
