name: MCPQ
main: org.mcpq.main.MCPQPlugin
version: 1.0
description: "Minecraft Protobuf Queries (MCPQ): Direct communication with and control of server"
api-version: 1.18
author: Felix Wallner
#commands:
#  testcmd:
#    description: Some command
